spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
          jdbc:
            lob:
              non_contextual_creation: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  http:
    encoding:
        charset: UTF-8
        enabled: true
        force: true
  mustache:
    prefix: file:src/main/resources/templates/
    suffix: .mustache
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    content-type: text/html
    charset: UTF-8
    enabled: true
    enable-debug: true
server:
  servlet:
    encoding:
      force-response: true